[package]
name = "sodium-macros"
version = "0.1.0"
authors = ["burgerguy"]
description = "external macros for sodium's rust packages"
keywords = ["proc_macro"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1.0"
syn = {version = "2.0", features = ["full"]}

