name: gradle-ci

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Fetch iris
      uses: actions/checkout@v2
      with:
        repository: 'IrisShaders/Iris'
        ref: 'trunk'
        path: 'iris'
    - name: Iris publishToMavenLocal
      run: cd ./iris && ./gradlew publishToMavenLocal && cd ..
    - name: Build artifacts
      run: ./gradlew build
