name: Verify Issue
on:
  issues:
    types:
      - opened
      - edited
      - reopened
jobs:
  moderate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: verify-issue
        with:
          result-encoding: string
          script: |
            const issue_payload = context.payload.issue;
            const issue_content = issue_payload.body;
            if (issue_payload.pull_request != null || !issue_content.startsWith("### Bug Description")) {
              return;
            }
            
            const author_name = issue_payload.user ? issue_payload.user.login : context.payload.sender.login;
            const LOG_FILE_REGEX = /### Log File[^]+?\[.+\.(txt|log)\]\(https:\/\/github\.com\/\w+\/sodium-fabric\/files\/\d+\/.+\.(txt|log)\)/;
            const CRASH_REPORT_REGEX = /### Crash Report[^]+?\[.+\.(txt|log)\]\(https:\/\/github\.com\/\w+\/sodium-fabric\/files\/\d+\/.+\.(txt|log)\)/;
            
            if (issue_payload.state == "open") {
              let match = LOG_FILE_REGEX.exec(issue_content);
              if (!match || !match[0].includes("### Crash Report")) {
                await github.rest.issues.update({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: "closed",
                  state_reason: "not_planned",
                  labels: ["E-invalid"],
                })
                await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: `@${author_name}, this issue was automatically closed because it did not follow the issue template. You either did not upload a log file or didn't upload it in the required format. Attach a log file and a crashlog as described in the issue template by dragging and dropping the file and letting GitHub create an attachment. Do not copy-paste the content of the log file into the area. Please edit your issue to add the required data and the issue will be automatically be reopened.`,
                });
              } else if (!CRASH_REPORT_REGEX.test(issue_content)) {
                await github.rest.issues.update({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: "closed",
                  state_reason: "not_planned",
                  labels: ["E-invalid"],
                })
                await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: `@${author_name}, this issue was automatically closed because it did not follow the issue template. You either did not upload a crash log or didn't upload it in the required format. Attach a log file and a crash log as described in the issue template by dragging and dropping the file and letting GitHub create an attachment. Do not copy-paste the content of the log file into the area. Please edit your issue to add the required data and the issue will be automatically be reopened.`,
                });
              }
            } else if (issue_payload.labels.some(label => label.name == "E-invalid") && LOG_FILE_REGEX.test(issue_content) && CRASH_REPORT_REGEX.test(issue_content)) {
              await github.rest.issues.update({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: "open",
              })
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "Reopened because the issue now follows the issue template.",
              });
            }
